/** 演示数据 — 脱敏处理 */

export const seedUsers = [
  {
    id: 'user-zhangsan',
    username: 'zhangsan',
    passwordHash: '$2b$10$dummyhashzhangsan', // demo123
    name: '张三',
    role: 'initiator',
    department: '智慧住居事业部',
    domain: 'smart_living',
  },
  {
    id: 'user-lisi',
    username: 'lisi',
    passwordHash: '$2b$10$dummyhashlisi',      // demo123
    name: '李四',
    role: 'supervisor',
    department: '智慧住居事业部',
    domain: 'smart_living',
  },
  {
    id: 'user-wangwu',
    username: 'wangwu',
    passwordHash: '$2b$10$dummyhashwangwu',    // demo123
    name: '王五',
    role: 'group_approver',
    department: '集团战略投资部',
    domain: 'smart_living',
  },
  {
    id: 'user-admin',
    username: 'admin',
    passwordHash: '$2b$10$dummyhashadmin',      // admin123
    name: '曹智',
    role: 'admin',
    department: '集团战略投资部',
    domain: 'smart_living',
  },
  {
    id: 'user-ceo',
    username: 'ceo',
    passwordHash: '$2b$10$dummyhashceo',        // demo123
    name: '陈总',
    role: 'viewer',
    department: '集团管理层',
    domain: 'smart_living',
  },
];

export const seedFilings = [
  {
    id: 'filing-001',
    filingNumber: 'BG20250301-001',
    type: 'equity_direct',
    projectStage: 'invest',
    title: '海川项目首次投资',
    description: '智慧住居领域海川项目直投投资，投资金额2亿元',
    projectName: '海川项目',
    legalEntityName: '海川科技有限公司',
    domain: 'smart_living',
    industry: '住居科技',
    amount: '20000.00',
    currency: 'CNY',
    investmentRatio: '30.00',
    valuationAmount: '66667.00',
    originalTarget: null,
    newTarget: null,
    changeReason: null,
    approvalGroups: ['finance', 'strategy', 'legal'],
    emailRecipients: [],
    confirmedBy: 'user-admin',
    status: 'completed',
    riskLevel: null,
    creatorId: 'user-zhangsan',
    submittedAt: new Date('2025-03-01T10:00:00Z'),
    completedAt: new Date('2025-03-05T16:00:00Z'),
  },
  {
    id: 'filing-002',
    filingNumber: 'BG20251101-002',
    type: 'equity_direct',
    projectStage: 'change',
    title: '海川项目对赌目标调整（8000万→5000万）',
    description: '因市场环境变化，海川项目对赌目标从8000万调整为5000万',
    projectName: '海川项目',
    legalEntityName: '海川科技有限公司',
    domain: 'smart_living',
    industry: '住居科技',
    amount: '5000.00',
    currency: 'CNY',
    investmentRatio: null,
    valuationAmount: null,
    originalTarget: '8000.00',
    newTarget: '5000.00',
    changeReason: '市场环境变化，原对赌目标不可达，经双方协商调整',
    approvalGroups: ['finance', 'strategy'],
    emailRecipients: [],
    confirmedBy: 'user-admin',
    status: 'completed',
    riskLevel: null,
    creatorId: 'user-zhangsan',
    submittedAt: new Date('2025-11-01T09:00:00Z'),
    completedAt: new Date('2025-11-08T14:00:00Z'),
  },
  {
    id: 'filing-003',
    filingNumber: 'BG20260201-003',
    type: 'fund_project',
    projectStage: 'invest',
    title: '星辰基金项目新增备案',
    description: '产业金融领域星辰基金投资项目备案',
    projectName: '星辰基金',
    legalEntityName: null,
    domain: 'industrial_finance',
    industry: '金融投资',
    amount: '15000.00',
    currency: 'CNY',
    investmentRatio: null,
    valuationAmount: null,
    originalTarget: null,
    newTarget: null,
    changeReason: null,
    approvalGroups: ['finance', 'strategy', 'audit'],
    emailRecipients: [],
    confirmedBy: 'user-admin',
    status: 'completed',
    riskLevel: null,
    creatorId: 'user-zhangsan',
    submittedAt: new Date('2026-02-01T08:30:00Z'),
    completedAt: new Date('2026-02-10T11:00:00Z'),
  },
  {
    id: 'filing-004',
    filingNumber: 'BG20260205-004',
    type: 'legal_entity',
    projectStage: 'invest',
    title: '创新科技法人新设',
    description: '智慧住居领域新设创新科技有限公司',
    projectName: '创新科技项目',
    legalEntityName: '创新科技有限公司',
    domain: 'smart_living',
    industry: '住居科技',
    amount: '5000.00',
    currency: 'CNY',
    investmentRatio: '100.00',
    valuationAmount: '5000.00',
    originalTarget: null,
    newTarget: null,
    changeReason: null,
    approvalGroups: ['finance', 'hr', 'strategy', 'legal'],
    emailRecipients: [],
    confirmedBy: 'user-admin',
    status: 'completed',
    riskLevel: null,
    creatorId: 'user-zhangsan',
    submittedAt: new Date('2026-02-05T14:00:00Z'),
    completedAt: new Date('2026-02-12T09:00:00Z'),
  },
  {
    id: 'filing-005',
    filingNumber: 'BG20260301-005',
    type: 'equity_direct',
    projectStage: 'change',
    title: '海川项目对赌目标调整（5000万→3000万）',
    description: '海川项目对赌目标从5000万进一步调整为3000万，第二次调整',
    projectName: '海川项目',
    legalEntityName: '海川科技有限公司',
    domain: 'smart_living',
    industry: '住居科技',
    amount: '3000.00',
    currency: 'CNY',
    investmentRatio: null,
    valuationAmount: null,
    originalTarget: '5000.00',
    newTarget: '3000.00',
    changeReason: '持续经营压力，对赌目标需再次下调',
    approvalGroups: ['finance', 'strategy'],
    emailRecipients: [],
    confirmedBy: null,
    status: 'pending_business',
    riskLevel: null,
    creatorId: 'user-zhangsan',
    submittedAt: new Date('2026-03-01T10:00:00Z'),
    completedAt: null,
  },
];

export const seedApprovals = [
  // filing-001 审批记录 (business → group → confirmation)
  {
    id: 'approval-001-b1',
    filingId: 'filing-001',
    approverId: 'user-lisi',
    approverName: '李四',
    stage: 'business',
    level: 1,
    groupName: null,
    status: 'approved',
    comment: '同意，海川项目符合战略方向',
    decidedAt: new Date('2025-03-02T10:00:00Z'),
  },
  {
    id: 'approval-001-g1',
    filingId: 'filing-001',
    approverId: 'user-wangwu',
    approverName: '王五',
    stage: 'group',
    level: 1,
    groupName: 'finance',
    status: 'approved',
    comment: '财务审核通过',
    decidedAt: new Date('2025-03-03T14:00:00Z'),
  },
  {
    id: 'approval-001-g2',
    filingId: 'filing-001',
    approverId: 'user-wangwu',
    approverName: '王五',
    stage: 'group',
    level: 1,
    groupName: 'strategy',
    status: 'approved',
    comment: '同意备案',
    decidedAt: new Date('2025-03-04T09:00:00Z'),
  },
  {
    id: 'approval-001-c1',
    filingId: 'filing-001',
    approverId: 'user-admin',
    approverName: '曹智',
    stage: 'confirmation',
    level: 1,
    groupName: null,
    status: 'approved',
    comment: '确认备案',
    decidedAt: new Date('2025-03-05T16:00:00Z'),
  },
  // filing-005 待审批（当前 business 阶段）
  {
    id: 'approval-005-b1',
    filingId: 'filing-005',
    approverId: 'user-lisi',
    approverName: '李四',
    stage: 'business',
    level: 1,
    groupName: null,
    status: 'pending',
    comment: null,
    decidedAt: null,
  },
];
